services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - ["setFramework", ["@contao.framework"]]

    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - ["setContainer", ["@service_container"]]

  mvo_contao_facebook.listener.import_posts:
    class: 'Mvo\ContaoFacebook\EventListener\ImportFacebookPostsListener'

  mvo_contao_facebook.listener.import_events:
    class: 'Mvo\ContaoFacebook\EventListener\ImportFacebookEventsListener'

  mvo_contao_facebook.listener.open_graph_tags:
    class: 'Mvo\ContaoFacebook\EventListener\AddOpenGraphTagsListener'